### ISSUE TITLE
DLL load failed while importing PPTBFModel:

### ISSUE THREAD

**Issue by jiayaozhang** [yiwei-hu/SVBRDF-Proceduralization#3]
Thanks for your great work, I am trying to implement this code but found that when i run `python main.py`
it shows below errors, could you help with this, many thanks!

``` python .\main.py                                                          
Traceback (most recent call last):                                                                                                                                   
File "D:\JainiceResearch\SVBRDF-Proceduralization-main\SVBRDF-Proceduralization-main\main.py", line 6, in <module>                                                    from matting.interface import start_app                                                                                                                           
File "D:\JainiceResearch\SVBRDF-Proceduralization-main\SVBRDF-Proceduralization-main\matting\interface.py", line 22, in <module>                                      from multi_material import MultiMaterial                                                                                                                          
File "D:\JainiceResearch\SVBRDF-Proceduralization-main\SVBRDF-Proceduralization-main\multi_material.py", line 11, in <module>                                         from PPTBF.PPTBF import PPTBFFitter                                                                                                                              
File "D:\JainiceResearch\SVBRDF-Proceduralization-main\SVBRDF-Proceduralization-main\PPTBF\PPTBF.py", line 9, in <module>                                             import PPTBF.PPTBFModel as PPTBFModel                                                                                                                          
ImportError: DLL load failed while importing PPTBFModel: 找不到指定的模块。       
```

**Comment by jiayaozhang** [comment]
Also what is graph.torch, how could it be provided?

```python 
File "C:\Users\Admin\miniconda3\envs\SVBRDF_proceduralization\lib\site-packages\torch\serialization.py", 
line 251, in __init__                                                       
super(_open_file, self).__init__(open(name, mode))  
FileNotFoundError: [Errno 2] No such file or directory: './samples/mosaic\\results\\synthesis_results\\graph.torch'
```

**Comment by yiwei-hu** [comment]
Hi, for the first question, can you double check that your `PPTBF` folder is not empty? The `main.py` will import a module from that folder. There also might be some incompatibility issues. The code was tested with Python 3.7 on Windows 10. 

Regarding the second one, the file `graph.torch` is generated after you run `synthesize()` function which stores the optimized parameters. It can be then used in `resynthesize()` function.

**Comment by vixyzvv** [comment]
I also meets the first question, and i think you should try reinstall in a new computer without any environment, and you will find many problems in preparing environment.

1. matlabengine not support in python3.7, so you should not set conda python version 3.7.

3.7:

![18e0114b8c438aa815914a4aa31812e](https://user-images.githubusercontent.com/74554469/227766789-8bf8808f-0367-4913-b661-2041769b1aca.png)

3.8:

![30b2febe3c10de6483177f939ca0e62](https://user-images.githubusercontent.com/74554469/227766804-9f1b3fb6-dd2a-4264-b99b-db9a8e07ca2b.png)

2. `conda install pytorch torchvision cudatoolkit=11.3 -c pytorch` is a command to install a cpu version pytorch. the link below is solution: 

https://blog.csdn.net/qq_46126258/article/details/112708781

3. I also meets "importing PPTBFModel" problem.

![67f4efda01dc58fd32920468a500104](https://user-images.githubusercontent.com/74554469/227767240-0582b37c-9606-48f0-9d6e-c811fafcf5b9.png)

PPTBF folder: 

![1679823378315](https://user-images.githubusercontent.com/74554469/227767289-54c722db-0ba5-4b15-a2ee-2ecf0a42cf6c.png)

the folder is cloned from your repo, why you feel it is empty?

so many problems in preparing environment, and i waste a day for fixing them.

**Comment by jiayaozhang** [comment]
```python
During handling of the above exception, another exception occurred:
Traceback (most recent call last): 
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\visdom\__init__.py", 
line 240, in _send data=json.dumps(msg), 
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\requests\api.py", line 115, 
in post return request("post", url, data=data, json=json, **kwargs) 
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\requests\api.py", line 59, in request        
return session.request(method=method, url=url, **kwargs)                                   
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\requests\sessions.py", line 587, in request   
resp = self.send(prep, **send_kwargs)    
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\requests\sessions.py", line 701, in send          
r = adapter.send(request, **kwargs)                                                                                
File "C:\Users\jiaya\anaconda3\envs\SVBRDF\lib\site-packages\requests\adapters.py", line 567, in send                         
raise ConnectionError(e, request=request)                                                                            
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): 
Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection 
object at 0x0000029601084E48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')) 
```



After solving the PPTBF problem by make it all through `torch.device("cpu")` and while run `synthesize()` encounter NewConnectionError problem above. Have you had any similar problems and how to solve this, many thanks

**Comment by yiwei-hu** [comment]
@virgilwjj The code was tested with Python 3.7 + Matlab 2021b on a Windows machine. As specified in the instruction, Python 3.7 is required because the PPTBF wrapper is compiled for Python 3.7. However, notice that Matlab 2022b doesn't support Python 3.7 any more. We recommend you use eariler version of Matlab. 

If you have trouble with installing PyTorch, please check PyTorch official website for the most recent commands. Different hardware/software configurations may cause problems.

**Comment by yiwei-hu** [comment]
@jiayaozhang It seems like a problem from visdom. Did you start a visdom server (see Line 34 in main.py) before you run `synthesize()`? The visdom is used to plot losses. You can also disable this functionality by commenting out Line 42, 77 and 78 in `optimizer.py`.

**Comment by jiayaozhang** [comment]
I solve my problem, thanks! 🎉🎉🎉
